### ISSUE TITLE
cloud-init not removed -- runcmd

### ISSUE THREAD

**Issue by piphoto** [giovtorres/kvm-install-vm#4]
Hi first off all i love this little script, use it for all my vm creations on kvm.

In your script there is the runcmd which supposedly should remove cloud-init but on my system it does not. When i shutdown the vm and start it again, i see cloud-init is starting all over again. And the boot time is very long.

This is the output from: /var/log/cloud-init.log

2017-11-06 08:05:25,660 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/luckyme/sem/config_runcmd'>)
Cloud-init v. 0.7.9 running 'modules:config' at Mon, 06 Nov 2017 13:05:24 +0000. Up 13.55 seconds.
2017-11-06 08:05:25,660 - util.py[WARNING]: Failed to shellify [['apt-get', '-y', 'remove', 'cloud-init'], None] into file /var/lib/cloud/instances/luckyme/scripts/runcmd
2017-11-06 08:05:25,660 - util.py[WARNING]: Failed to shellify [['apt-get', '-y', 'remove', 'cloud-init'], None] into file /var/lib/cloud/instances/luckyme/scripts/runcmd
2017-11-06 08:05:25,660 - util.py[DEBUG]: Failed to shellify [['apt-get', '-y', 'remove', 'cloud-init'], None] into file /var/lib/cloud/instances/luckyme/scripts/runcmd
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_runcmd.py", line 55, in handle
    content = util.shellify(cmd)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 1889, in shellify
    % (type_utils.obj_name(args)))
RuntimeError: Unable to shellify type NoneType which is not a list or string

**Comment by giovtorres** [comment]
Hi @piphoto, could you give it a try now?

**Comment by piphoto** [comment]
Hi giovtorres, i gave it a try, it now seems that runcmd is running without problems. So cloud-init is indeed removed. However because of cloud-init removed at this stage, its not properly closing. I have the output of the full log. Also notice that the network fails to restart, so no new lease is asked. 
[cloud-init.log](https://github.com/giovtorres/kvm-install-vm/files/1446543/cloud-init.log)

**Comment by giovtorres** [comment]
Ok, I think I got it now.  I had the wrong restart command for ubuntu/debian.  `network` should have been `networking`.  See deecbd5.  Works for me now on debian9, centos7 and ubuntu1604.

**Comment by giovtorres** [comment]
Thanks @piphoto for pointing this out.  I will add some tests to check each OS, as I typically stick with CentOS7.

How were you planning to use this in combination with packer?
